metadata:
  scenario: demo
  seed: 42
  num_objects: 12
  generated_by: tools/make_seabed.py
objects:
- id: 0
  class: debris
  x: 33.26
  y: -5.95
  z: -15.0
  size_m: 1.085
  source_image: ml/data/raw/trashcan/dataset/instance_version/train/vid_000076_frame0000032.jpg
  source_split: test
- id: 1
  class: debris
  x: 16.23
  y: -9.8
  z: -15.0
  size_m: 0.704
  source_image: ml/data/raw/trashcan/dataset/instance_version/train/vid_000287_frame0000006.jpg
  source_split: test
- id: 2
  class: debris
  x: 14.15
  y: 10.16
  z: -15.0
  size_m: 0.681
  source_image: ml/data/raw/trashcan/dataset/instance_version/train/vid_000169_frame0000010.jpg
  source_split: test
- id: 3
  class: debris
  x: 35.87
  y: -1.76
  z: -15.0
  size_m: 1.083
  source_image: ml/data/raw/trashcan/dataset/instance_version/val/vid_000143_frame0000012.jpg
  source_split: test
- id: 4
  class: debris
  x: 15.32
  y: -1.83
  z: -15.0
  size_m: 0.735
  source_image: ml/data/raw/trashcan/dataset/instance_version/train/vid_000142_frame0000010.jpg
  source_split: test
- id: 5
  class: starfish
  x: 35.9
  y: -10.03
  z: -15.0
  size_m: 0.246
  source_image: ml/data/raw/duo/DUO/images/test/86.jpg
  source_split: test
- id: 6
  class: starfish
  x: 35.08
  y: 6.1
  z: -15.0
  size_m: 0.205
  source_image: ml/data/raw/duo/DUO/images/test/188.jpg
  source_split: test
- id: 7
  class: starfish
  x: 32.16
  y: 1.75
  z: -15.0
  size_m: 0.294
  source_image: ml/data/raw/duo/DUO/images/test/1014.jpg
  source_split: test
- id: 8
  class: sea_urchin
  x: 17.46
  y: 6.13
  z: -15.0
  size_m: 0.1
  source_image: ml/data/raw/duo/DUO/images/test/299.jpg
  source_split: test
- id: 9
  class: sea_urchin
  x: 13.75
  y: 1.94
  z: -15.0
  size_m: 0.107
  source_image: ml/data/raw/duo/DUO/images/test/4.jpg
  source_split: test
- id: 10
  class: scallop
  x: 34.75
  y: 10.15
  z: -15.0
  size_m: 0.125
  source_image: ml/data/raw/duo/DUO/images/test/1006.jpg
  source_split: test
- id: 11
  class: scallop
  x: 13.74
  y: -5.76
  z: -15.0
  size_m: 0.113
  source_image: ml/data/raw/duo/DUO/images/test/142.jpg
  source_split: test
