controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - Joint_FR
      - Joint_FL
      - Joint_MR
      - Joint_ML
      - Joint_BR
      - Joint_BL
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
